### ISSUE TITLE
Listed Magisk build no longer available

### ISSUE THREAD

**Issue by Zylanx** [DorianRudolph/pinenotes#1]
The listed Magisk build [c85b2a0](https://github.com/canyie/Magisk/actions/runs/1627522914) seems to have been deleted and is no longer valid.
What would the next best build to use be?

**Comment by Zylanx** [comment]
Nevermind. The backup link still works. Could have sworn I clicked on it and it showed a 404. Must have clicked on the commit link next to it.

Closing

**Comment by DorianRudolph** [comment]
The canary build should also work, the fix is in master now https://github.com/topjohnwu/Magisk/commit/880b348ce66750a77d446270509d73bfc411600b
