### ISSUE TITLE
About rooting with Magisk

### ISSUE THREAD

**Issue by ltlnx** [DorianRudolph/pinenotes#2]
Hello,

I followed the instructions from the guide for rooting (https://github.com/DorianRudolph/pinenotes#magisk), but after I issued `rkdeveloptool reboot`, the device stayed powered off (or at least stated by the screen). No sign of it rebooting.

Normally, how long does the boot process take? Should I wait for longer for it to boot?

Also, is there a way to hard reset or force shutdown the Pinenote? I didn't find it in the Pinenote wiki or guides.

Thanks in advance!

**Comment by ltlnx** [comment]
As a side note, sometimes when I connect the Pinenote to my PC, `lsusb` shows
```
Bus 001 Device 014: ID 18d1:d001 Google Inc. Nexus 4 (fastboot)
```
but the device is in adb mode:
```
$ adb devices
List of devices attached
PNOTE200421AL40000730   unauthorized
```
and the screen stays in the logo, no boot indicaton or anything.

**Comment by DorianRudolph** [comment]
Did you remove the magnet before rebooting? The boot process shouldn't take more than a minute I think. Holding the power button for about 10 seconds should reset the PineNote. Have you tried that? What does it output on the serial console? I assume you flashed the patched uboot.img. Can you flash the original back and then boot?

If it shows up as Nexus, then it is in recovery mode, but I don't know if the recovery mode does anything useful. I think it is supposed to go into recovery mode if you place the magnet with screen up. So make sure the screen is facing down.

Hope this helps

**Comment by ltlnx** [comment]
Thanks for the reply!

I backed up the boot partition as `boot.img` and patched the image as `boot_magisk.img`. They are two different files:
```
$ ls -a                                             
.  ..  boot.img  boot_magisk.img  uboot.img
$ md5sum boot.img                                   
3fae6e30238654d99c1eb05bbb86b469  boot.img
$ md5sum boot_magisk.img
bdb52737c0a3944ff907288e26bb2c2c  boot_magisk.img
```
and I flashed the original back. Funny thing is, after issuing `rkdeveloptool reboot` for the first time, the device still stays in loader mode; after the second time, the device finally disonnected.
```
$ rkdeveloptool write-partition boot boot.img
Write LBA from file (100%)
$ rkdeveloptool reboot
Reset Device OK.
$ rkdeveloptool list
DevNo=1 Vid=0x2207,Pid=0x350a,LocationID=101    Loader
$ rkdeveloptool reboot
Reset Device OK.
$ rkdeveloptool list
No devices in rockusb mode found
```
All this happened with the device plugged in and the screen on the Pinenote logo, no refreshing or stuff. I removed the pen after the first `reboot` command. But after flashing the original boot image, the Pinenote still didn't boot.

Holding the power button for 10 seconds doesn't yield any results on the screen, but it seems to shut down the device, as I can place the pen and go into rockchip mode again.

BTW where should the serial console output be? Also do you have the original `boot.img` backup of your device? If so, I would love to test flashing your boot image and see if that resurrects the device.

**Comment by DorianRudolph** [comment]
My boot.img is in `/static` of this repository. Here is my [full backup](https://1drv.ms/u/s!AuBFUYtk7aRLxSpIleR55b3io2a0?e=z9bRea) (though the userdata partition is broken, but that shouldn't be an issue here).

Looks like you didn't read the "fix uboot" section ^^

Because I can recreate your md5sum by replacing the last 36700160 bytes in my boot.img with 0xCC (check with a hex editor).
But it should be all good if you flash the boot.img from this repo.

For the serial console, you need to connect the little adapter to the pinenote and then `picocom /dev/ttyUSB0 -b 1500000 -l` (many other programs also work).

**Comment by ltlnx** [comment]
Only writing `boot.img` doesn't work, but writing all of the partitions back works! Thanks!
Moving on to patch the boot.img again :)
